<?php
require("./".$prefijo."db/db.tbAccion.php");
require("./".$prefijo."db/db.tbCiudad.php");
require("./".$prefijo."db/db.tbLogUsuarioXReceta.php");
require("./".$prefijo."db/db.tbPaso.php");
require("./".$prefijo."db/db.tbPasoReceta.php");
require("./".$prefijo."db/db.tbProvincia.php");
require("./".$prefijo."db/db.tbReceta.php");
require("./".$prefijo."db/db.tbRecetaDesbloqueada.php");
require("./".$prefijo."db/db.tbUsuario.php");
require("./".$prefijo."db/db.tbSession.php");
?>